### ISSUE TITLE
[BUG]运行程序即出现报错

### ISSUE THREAD

**Issue by ImYiFeng** [KIYI671/AhabAssistantLimbusCompany#24]
![image](https://github.com/user-attachments/assets/78aedacf-da28-4dd0-a819-f538cb4ebe48)
Traceback (most recent call last):
  File "main.py", line 18, in <module>
  File "my_gui.py", line 636, in mygui
  File "my_gui.py", line 575, in read_last_setting
TypeError: 'NoneType' object is not subscriptable

**Comment by KIYI671** [comment]
请参考https://github.com/KIYI671/AhabAssistantLimbusCompany/issues/8

**Comment by ImYiFeng** [comment]
> 请参考#8

感谢指路
